language: java
jdk:
  - openjdk11
env:
  global:
    - HUGO_VERSION=0.67.1
install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb"
  - sudo dpkg -i "hugo_${HUGO_VERSION}_Linux-64bit.deb"
  - nvm install 8
script:
  # 1. build main site assets: js, css, etc.
  - cd app && npm run build
  # 2. build docs
  - cd .. && ./build-asciidocs.sh master
  # 3. run hugo
  - hugo
branches:
  only:
    - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  target_branch: gh-pages
cache:
  npm: true
  directories:
    - $HOME/.m2