baseURL = "http://example.org/"
languageCode = "en-us"
title = "Agrest"

[permalinks]
  page = ":filename/"

[[menu.main]]
  name = "Documentation"
  url = "/docs/"
  weight = 1

[[menu.main]]
  name = "Forum"
  url = "https://groups.google.com/forum/?#!forum/agrest-user"
  weight = 2